# Server info
server:
  servlet:
    context-path: /ezlinker
  port: 2500
# Spring config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3308/ezlinker?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=NO
      username: root
      password: root
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: password
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  redis:
    database: 0
    host: 10.168.1.214
    # password: redis
    port: 6379
    timeout: 300

  data:
    mongodb:
      uri: mongodb://localhost:27017
      # password: guest
      # username: guest
      port: 27017
      database: ezlinker
      authentication-database: admin

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false

logging:
  level:
    root: info
    org.springframework.data.mongodb.core: DEBUG
    com.baomidou.mybatisplus.core.mapper: DEBUG
